[build]
builder = "nixpacks"

[deploy]
startCommand = "python copy_db.py && gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[mounts]
source = "data"
destination = "/data"
