const test=require('node:test');const assert=require('node:assert/strict');
const {newOverviewMoney,newOverviewNumber,newOverviewChange,newOverviewPriceCoverage,calculateNewHistoricalChanges,renderNewPortfolioOverview}=require('../static/new-portfolio-overview.js');
test('new overview formats money, quantities and changes',()=>{assert.equal(newOverviewMoney(1234),"$1'234.00");assert.equal(newOverviewNumber(1.234567891),'1.23456789');assert.equal(newOverviewChange(-2),'-2.00%');assert.equal(newOverviewChange(null),'Unavailable');});
test('new historical changes use compact snapshots',()=>{const result=calculateNewHistoricalChanges({comparisons:{change24h:{total_value:100,datetime:'2026-09-01'}}},125);assert.equal(result.change24h.value,25);assert.equal(result.change24h.percent,25);assert.equal(result.change7d,null);});
test('new overview explains complete, stale and missing price coverage',()=>{assert.equal(newOverviewPriceCoverage({priced_assets:12,required_assets:12,complete:true,stale:[],sources:['CoinGecko','Kraken']}),'Price coverage: 12/12 assets. Kraken uses the latest available ticker prices; CoinGecko crypto quotes are at most 15 minutes old.');assert.match(newOverviewPriceCoverage({priced_assets:11,required_assets:12,complete:false,stale:[],sources:[]},['ETH']),/Missing: ETH/);assert.match(newOverviewPriceCoverage({priced_assets:12,required_assets:12,complete:true,stale:['BTC'],sources:['CoinGecko']}),/Last-known prices.*BTC/);});
test('new overview renders a grouped xStocks row with only its combined value',()=>{
 const nodes=new Map();const el=()=>({textContent:'',title:'',src:'',alt:'',children:[],className:'',classList:{values:[],add(...v){this.values.push(...v);}},replaceChildren(){this.children=[];},appendChild(c){this.children.push(c);}});global.document={getElementById(id){if(!nodes.has(id))nodes.set(id,el());return nodes.get(id);},createElement:el};
 try{renderNewPortfolioOverview({total_value_usd:500,btc_value:5,monthly_yield_usd:0,complete:true,unpriced_assets:[],price_quality:{priced_assets:1,required_assets:1,complete:true,stale:[],sources:['Kraken']},as_of:'2026-09-01T00:00:00Z',assets:[{asset:'xStocks',is_xstocks:true,total_balance:null,price:null,total_value:500,image:null,hourly_change:null,daily_change:null,seven_day_change:null,origins:['Kraken']}]});assert.equal(nodes.get('newPortfolioTotal').textContent,'$500.00');assert.match(nodes.get('newPortfolioQuality').textContent,/Price coverage: 1\/1 assets/);const cells=nodes.get('newPortfolioOverviewRows').children[0].children;assert.equal(cells.length,7);assert.equal(cells[0].children[0].children[1].textContent,'xStocks');assert.equal(cells[0].children[0].children[1].title,'Origins: Kraken');for(let index=1;index<=5;index++)assert.equal(cells[index].textContent,'');assert.equal(cells[6].textContent,'$500.00');}finally{delete global.document;}
});
